# Generated by Django 3.2.4 on 2021-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_filesupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='myfiles',
        ),
    ]
